### ISSUE TITLE
JSONAssert has undeclared dependency on org.json.JSONArray

### ISSUE THREAD

**Issue by sergeykad** [skyscreamer/JSONassert#170]
Using JSONAssert library produces the compilation error seen below if 'org.json:json' was not added as a dependency too.

```
cannot access JSONArray
            JSONAssert.assertEquals(expected, actual,
                      ^
  class file for org.json.JSONArray not found
```

**Comment by martypitt** [comment]
Just hit this too...

```
java.lang.NoClassDefFoundError: org/json/JSONException

	at org.skyscreamer.jsonassert.JSONCompare.compareJSON(JSONCompare.java:49)
	at org.skyscreamer.jsonassert.JSONCompare.compareJSON(JSONCompare.java:125)
```
