### ISSUE TITLE
"null" is valid JSON

### ISSUE THREAD

**Issue by gimmi** [skyscreamer/JSONassert#83]
The following example:

```java
JSONAssert.assertEquals("null", "null", false);
```

result in this exception:

```
org.json.JSONException: Unparsable JSON string: null
```

but `null` is valid JSON, even at the "root" level according to [THIS](http://stackoverflow.com/a/39124954/66629)

**Comment by gimmi** [comment]
Is project dead?

**Comment by rehevkor5** [comment]
An example (partial) stack trace due to this problem happening in Spring controller tests:

```
org.json.JSONException: Unparsable JSON string: null

	at org.skyscreamer.jsonassert.JSONParser.parseJSON(JSONParser.java:56)
	at org.skyscreamer.jsonassert.JSONCompare.compareJSON(JSONCompare.java:49)
	at org.skyscreamer.jsonassert.JSONCompare.compareJSON(JSONCompare.java:125)
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:415)
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:394)
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:336)
	at org.springframework.test.util.JsonExpectationsHelper.assertJsonEqual(JsonExpectationsHelper.java:61)
	at org.springframework.test.web.servlet.result.ContentResultMatchers.lambda$json$9(ContentResultMatchers.java:217)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:196)
...
```
